package com.cubivue.inlogic

import com.cubivue.inlogic.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication

/**
 * Initialization of libraries.
 */
class MainApplication : DaggerApplication() {

    override fun onCreate() {
        super.onCreate()

    }

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.google.samples.apps.iosched.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(this)
    }
}
